spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pigshortrent?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: org.lanqiao.entity

#showSql
logging:
  level:
    org:
      lanqiao:
        mapper: debug
#pagehelper 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

