spring:
  datasource:
    username: root
    password: 571690530
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
file:
  location:
    path: D:/upload


mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: org.lanqiao.entity

#showSql
logging:
  level:
    org:
      lanqiao:
        mapper: debug

  #文件大小 MB必须大写
  #  maxFileSize 是单个文件大小
  #  maxRequestSize是设置总上传的数据大小



